### ISSUE TITLE
Gradle 7 compatibility

### ISSUE THREAD

**Issue by vojkny** [jprante/gradle-plugin-jflex#18]
Hi,

it seems the plugin is not very friendly with Gradle 7 – it complaints about this:

https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation

**Comment by john-hix** [comment]
I don't receive the error when running my Gradle build. I would guess that fd7b97a fixed this (EDIT: by "this", I mean the specific error knyttl pointed out), based on the date, description, and a skim of the changes.

@jprante or @dcabasson, could you confirm or CMIIW? Thank you.

**Comment by jprante** [comment]
Update to Gradle 7.3.2 is now in 1.6.0

https://plugins.gradle.org/plugin/org.xbib.gradle.plugin.jflex
