### ISSUE TITLE
gradle.org reports incorrect repository

### ISSUE THREAD

**Issue by imoverclocked** [jprante/gradle-plugin-jflex#8]
https://plugins.gradle.org/plugin/org.xbib.gradle.plugin.jflex/1.2.0

 * They point to the (defunct) URL: https://github.com/xbib/gradle-plugin-jflex
 * If you have taken the plugin over, you should update that to point at your repo
   * Thanks for taking it over!

**Comment by jprante** [comment]
Thank you for using my plugin.

I moved the plugin fomr my other project account 'xbib' to 'jprante' because it is not a bibliographic programming project.

1.2.1 solves the issue.
